### ISSUE TITLE
Finish implementing player houses

### ISSUE THREAD

**Issue by Lynaras** [nusku-co/conquergods#234] opened 2018-02-22 13:16 UTC
I took a HousePermit I bought from someone and 300k and tried to get a house, but the HouseAdmin took both and didn't give me a house. I tried re-logging to see if that would fix it but he is just asking for another permit.

**Comment by nusku-co** [comment] 2018-02-23 09:58
Actually, I am closing this since it's a duplicate of #86 . I'll use that issue to track player houses instead

**Closed as completed by nusku-co** 2018-02-23 09:58 UTC
Labels: Missing Feature
